config/routes.rb
Rails.application.routes.draw do
  root to: 'votes#entrance'
  get 'signin/:id' => 'votes#signin_form'
  post "valid" => "votes#validate"
  get "candidates/:id" => "votes#candidates"
  post "vote" => "votes#vote"
  post "logout" => "votes#logout"
  get "thx/:id" => "votes#thx"
  get "no_event" => "votes#no_event"
  namespace :admin do
    root to: 'votes#entrance'
    get 'sysrc' => 'votes#sysrc_monitor'
    get 'download_log/:log_id' => 'votes#download_log', as: "download_log"
    get 'select' => 'votes#select'
    post 'valid' => 'votes#valid'
    get 'events' => 'events#event_list'
    get 'events/new_event' => 'events#new_event'
    post 'events/create_event' => 'events#create_event'
    get 'events/new_voter' => 'events#new_voter'
    post 'events/create_voter' => 'events#create_voter'
    post 'events/import_voter' => 'events#import_voter'
    get 'voter/del/:id' => 'events#del_voter'
    get 'events/:id/new_candidate' => 'events#new_candidate'
    post 'events/create_candidate' => 'events#create_candidate'
    post 'events/import_candidate' => 'events#import_candidate'
    get 'edit_info/:id' => 'events#edit_info'
    get 'edit_voters/:id' => 'events#edit_voters'
    get 'edit_candidates/:id' => 'events#edit_candidates'
    patch 'update_info/:id' => 'events#update_info'
    get 'candidate/del/:id' => 'events#del_candidate'
    get 'event/:id' => 'events#event_statistics'
    get 'permissions' => 'permissions#list'
    get 'event/del/:id' => 'events#del_event'
    post 'create_white' => 'permissions#create_white'
    get 'white/del/:id' => 'permissions#del_white'
    post 'create_admin' => 'permissions#create_admin'
    get 'admin/del/:id' => 'permissions#del_admin'
    get 'logout' => 'votes#logout'
  end
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :candidate, counter_cache: true
  belongs_to :voter
  belongs_to :vote_event
  validate :legal_amount, :same_event, on: :create
  validates_uniqueness_of :candidate_id, scope: :voter_id # 同一投票者不可投複數票給同一候選人
  after_create :update_counter

  def legal_amount # 數量不能超過event的限制人數,不能投給同一人多票
    errors.add(:voter_id,"too much vote for a voter") if voter.votes.count >= vote_event.limit_amount
  end

  def same_event
    errors.add(:voter_id,"doesnt belongs to the same event with candidate") if vote_event_id != candidate.vote_event_id
  end

  def update_counter
    new_counter = vote_event.recount_voted
  end
end

app/controllers/admin/votes_controller.rb
class Admin::VotesController < ApplicationController
  before_action :ie_go_die, if: :is_ie?
  before_action :go_through_entry, if: :signin?, only: :entrance
  before_action :back_to_entry, if: :not_signin?, except: [:entrance, :valid]

  # 顯示後臺登入畫面
  def entrance;end

  # 驗證admin帳密
  def valid
    account,passwd = params[:account],params[:passwd]
    target_admin = Admin.validate account,passwd
    if target_admin
      session[:adtoken] = AdminToken.force_create target_admin,request.remote_ip
      render 'select',:layout => false
    else
      head 422
    end
  end

  # 登出
  def logout
    token=AdminToken.find_by_addr(request.remote_ip)
    if token.destroy
      render 'entrance', layout: false
    else
      head 500
    end
  end
  
  # 選擇權限或投票功能
  def select
    @step=2
  end

  # 主機資源監視器
  def sysrc_monitor
    @step=2
    @disk_usage=%x(df /dev/sda1 | grep sda1 | awk '{print $5}'|sed 's/%//').strip
    @ram_usage=%x(free | grep 'Mem' | awk '{print $3/$2*100}').to_i.to_s
    @cpu_usage=%x(top -bn1 | sed -n '/Cpu/p' | awk '{print $2}').to_i.to_s
    @files_count = %x(ls #{Rails.root.join("log")} | wc -l).to_i-2
  end

  # 下載log
  def download_log
    begin
      case params[:log_id]
      when "0000"
        send_file Rails.root.join('log','production.log'),filename: "latest.log"
      when /^\d{4}$/
        files_count = %x(ls #{Rails.root.join('log')} | wc -l).to_i - 2
        target_file = "logfile_"+%x(printf "%04d" #{files_count +1 - params[:log_id].to_i})+".log"
        send_file Rails.root.join('log',target_file),filename: "#{params[:log_id]}.log"
      else
        head 404
      end
    rescue
      head 404
    end
  end

  private

  # 將ie用戶從導向至別的頁面,勸導其更換瀏覽器
  def ie_go_die
    render file: "public/no_ie.html", layout: false
  end

  # 檢查瀏覽器是否爲ie
  def is_ie?
    return Browser.new(request.user_agent).ie?
  end

  # 將輸入的密碼SHA1加密後比對資料庫帳密是否有相對應記錄存在
  def can_pass? acc,pw
    pw = Digest::SHA1.hexdigest(pw)
    return Admin.exists? account: acc, passwd: pw
  end

  # 重導至後臺首頁
  def back_to_entry
    redirect_to '/admin'
  end
  
  # 檢查是否登入
  def signin?
    return AdminToken.where('addr = ? and expire_at >= ? and content = ?',request.remote_ip,Time.now,session[:adtoken]).any?
  end

  # 檢查是否登入，回傳反值
  def not_signin?
    return AdminToken.where('addr = ? and expire_at >= ? and content = ?',request.remote_ip,Time.now,session[:adtoken]).empty?
  end

  # 已登入則跳過登入畫面，直搗選擇畫面
  def go_through_entry
    redirect_to '/admin/select'
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  before_action :ie_go_die, if: :is_ie?
  before_action :rd_no_event, unless: :has_event?, only: :entrance
  before_action :rd_root, if: :has_event?, only: :no_event
  before_action :no_permission_action, if: :not_signin?, only: [:logout, :vote]
  before_action :remove_all_token, unless: :has_event?
  before_action :current_event, only: [:signin_form, :validate, :candidates, :vote, :thx]
  before_action :current_voter, only: [:vote, :candidates]
  before_action :set_event_param, only: [:signin_form, :candidates, :thx]
  def entrance
    # 顯示除了已經結束的投票列表，對應xhr無layout
    @events = VoteEvent.group_by_time
    if request.xhr?
      render 'entrance', layout: false
    end
  end

  def signin_form
    # 顯示登入的表單，但不允許直接GET網址
    request.xhr??render('signin_form',layout: false):head(404)
  end

  def validate # 前臺登入
    # 檢查帳密，給予登入token
    account,passwd = params[:account],params[:passwd]
    target_voter=Voter.validate @current_event,account,passwd
    if target_voter
      session[:token] = Token.force_create @current_event,target_voter,request.remote_ip
      @vote_title = @current_event.title
      @voter_name = target_voter.name
      if already_vote? @current_event,target_voter
        @deadline = @current_event.deadline
        render "thx", layout:false
      else
        @candidates = @current_event.candidates.order("unit ASC")
        @vote_id = @current_event.id
        render "candidates", layout: false, id: @vote_id
      end
    else
      head 422
    end
  end

  # 顯示候選人名單
  def candidates;end

  # 送出投票
  def vote
    # vote_targets->所選的候選人之id
    vote_targets = params[:vote_targets]
    vote_targets.each do |vt|
      @current_voter.votes.create(candidate_id: vt, vote_event: @current_event)
    end
    @deadline = @current_event.deadline
    @vote_title = @current_event.title
    render 'thx', layout: false
  end

  # 登出
  def logout
    # 找到對應的token，將其刪除
    Token.find_by(addr: request.remote_ip,content: session[:token]).destroy
    @events = VoteEvent.group_by_time
    session[:token]=nil
    render "entrance", layout: false
  end

  def thx
    if request.xhr?
      @deadline = @current_event.deadline
      render 'thx', layout: false
    else
      head 404
    end
  end

  # 顯示"沒有可參與的投票"的頁面
  def no_event;end

  private

  # 若爲IE轉址至特別的頁面,接著is_ie?用
  def ie_go_die
    render file: "public/no_ie.html", layout: false
  end

  # 透過browser這個gem,分析user_agent並判斷是何種瀏覽器
  def is_ie?
    Browser.new(request.user_agent).ie?
  end

  # 沒有token卻執行操作，回傳422(在前臺會重導向至入口)
  def no_permission_action
    head 422 if request.xhr?
  end

  # 設定投票id與投票title
  def set_event_param
    @vote_id = params[:id]
    @vote_title = VoteEvent.find(params[:id]).title
  end
  
  # 重導向至"無可參與投票"頁面
  def rd_no_event
    redirect_to '/no_event'
  end

  # 重導向至入口
  def rd_root
    redirect_to '/'
  end

  # 檢查有無合法token
  def signin?
    Token.where("addr = ? and expire_at >= ? and content = ?",request.remote_ip,Time.now,session[:token]).any?
  end

  # 檢查有無合法token(回傳相反的值)
  def not_signin?
    Token.where('addr = ? and expire_at >= ? and content = ?',request.remote_ip,Time.now,session[:token]).empty?
  end

  # 根據傳入id設定現在的投票
  def current_event
    begin
      @current_event = VoteEvent.find(params[:id])
    rescue
      head 404
    end
  end

  # 檢查有無可參與投票
  def has_event?
    return VoteEvent.available_events.any?
  end

  # 根據token與投票設定現在的投票人
  def current_voter
    @current_voter = Token.find_by(addr: request.remote_ip, vote_event: @current_event).voter
  end

  # 檢查"現在投票人" 是否已經對 "現在的活動"投過票
  def already_vote? event,voter
    return Vote.where(vote_event: event,voter: voter).any?
  end

  # 檢查"現在投票人" 是否已經對 "現在的活動"投過票(回傳相反值)
  def not_vote_yet?
    return Vote.where(vote_event: event,voter: voter).empty?
  end

  # 移除所有token
  def remove_all_token
    Token.delete_all
  end
end

app/helpers/votes_helper.rb
module VotesHelper
  def sp_input text,id=nil,type="text",required=true
    content_tag(:div,class: "form-group") do
      content_tag(:label,text,for: id,class: "form-label") +
      content_tag(:input,nil,type: type,placeholder: text,id: id,class: "form-input",required: required)
    end
  end

  def logout_btn
    content_tag(:button, '',class: 'btn',id: 'logout') do
      content_tag(:i,'',class: 'icon icon-back')+
        content_tag(:span,'登出')
    end
  end

  def tw_time source
    (source.year-1911).to_s+"年"+source.localtime.strftime('%2m月%2d日%2H點%2M分')
  end

  def to_word number
    case number
    when 1 then '一'
    when 2 then '二'
    when 3 then' 三'
    when 4 then '四'
    when 5 then '五'
    when 6 then '六'
    when 7 then '七'
    when 8 then '八'
    when 9 then '九'
    when 10 then '十'
    else "?"
    end
  end
end

app/views/admin/votes/_log_area.html.slim
p
  center
    mark[style="margin-top: 8vh"]
      label[style="font-size: 3.5vh;font-weight: 900;text-shadow: -1px 0px 1px white, 0px -1px 1px white, 1px 0px 1px white, 0px 1px 1px white"] ="下載Log檔"
  center
    div[style="width: 80vw;height: 40vh;overflow-x: hidden;overflow-y: scroll;padding-top: 2vh"]
      p
        label.title[style="font-size: 2.5rem;font-weight: 900"] 0000
        = link_to admin_download_log_path("0000"), class: "btn btn-lg btn-primary" do
          i.icon.icon-download
      hr
      p
        center
      - if @files_count > 0
        - (1..@files_count).each do |i|
          p
            - full_id = %x(printf "%04d" #{i})
            - filename = full_id
            label.title[style="font-size: 2.5rem;font-weight: 900"] = "#{filename}"
            = link_to admin_download_log_path(full_id), class: "btn btn-lg btn-primary" do
              i.icon.icon-download
          hr

app/views/admin/votes/_resource.html.slim
p
  center
    label[style="font-size: 3.5vh;font-weight: 900;text-shadow: -1px 0px 1px white, 0px -1px 1px white, 1px 0px 1px white, 0px 1px 1px white"] ="硬碟使用率#{@disk_usage}%"
  meter[min='0' max='100' high='70' value="#{@disk_usage}" style="width: 100vw"]
p
  center
    label[style="font-size: 3.5vh;font-weight: 900;text-shadow: -1px 0px 1px white, 0px -1px 1px white, 1px 0px 1px white, 0px 1px 1px white"] ="記憶體使用率#{@ram_usage}%"
  meter[min='0' max='100' high='70' value="#{@ram_usage}" style="width: 100vw"]
p
  center
    label[style="font-size: 3.5vh;font-weight: 900;text-shadow: -1px 0px 1px white, 0px -1px 1px white, 1px 0px 1px white, 0px 1px 1px white"] ="處理器使用率#{@cpu_usage}%"
  meter[min='0' max='100' high='70' value="#{@cpu_usage}" style="width: 100vw"]

app/views/admin/votes/_step.html.slim
ul.step
  li class="step-item#{' active'if step == 1}"
    a.tooltip href="#" data-tooltip="(´・ω・｀)"
      | 進入後台
  li class="step-item#{' active'if step == 2}"
    a.tooltip href="#" data-tooltip="後台在手天下我有！(´・ω・｀)"
      | 控制面板

app/views/admin/votes/entrance.html.slim
=sp_input "後台帳號","admin_account"
=sp_input "後台密碼","admin_passwd","password"
center.mt-10
  button.btn#gobackend
    |進入後台
    i.icon.icon-forward

app/views/admin/votes/select.html.slim
.module#permission-module[title="管理者的帳密新增、刪除"]
.module#vote-module[title="投票的新增、修改、刪除、結果查詢"]
button#admin-out.btn.btn-lg[title="從後臺登出"] 登出
button#to-sysrc.btn.btn-lg 線上系統監測

app/views/admin/votes/sysrc_monitor.html.slim
= render "resource"
= render "log_area"
button.btn.btn-lg#to-menu 返回主選單